// SPDX-FileCopyrightText: 2025-2026 Xianning Zhan
// SPDX-License-Identifier: BSD-3-Clause

// Portable glitch-free clock-gate model. ASIC and FPGA builds may replace this
// module with a characterized ICG or vendor clock-control primitive.
module clock_gate (
  // Ungated source clock and enable
  input  logic clk_i,
  input  logic en_i,

  // Gated clock output
  output logic clk_o
);

`ifdef ERISCV_FPGA
  // en_i is generated by source-clock posedge state and is stable before the
  // next BUFGCE enable sample. Do not infer a falling-edge control register.
  BUFGCE bufgce_i (
    .I (clk_i),
    .CE(en_i),
    .O (clk_o)
  );
`else
  assign clk_o = clk_i & en_i;
`endif

endmodule
