// SPDX-FileCopyrightText: 2025-2026 Xianning Zhan
// SPDX-License-Identifier: BSD-3-Clause

// Clock-gate wrapper. The ASIC target binds a characterized ICG; FPGA builds
// use the vendor primitive. Generic RTL keeps the existing simple model.
module clock_gate (
  // Ungated source clock and enable
  input  logic clk_i,
  input  logic en_i,

  // Gated clock output
  output logic clk_o
);

`ifdef ERISCV_PPA_GENERIC
  // PPA uses a technology-neutral combinational model; no PDK cell is
  // instantiated, so Yosys can map the gate using the selected Liberty.
  assign clk_o = clk_i & en_i;
`elsif ERISCV_ASIC
  sky130_fd_sc_hd__dlclkp_2 icg_i (
    .CLK  (clk_i),
    .GATE (en_i),
    .GCLK (clk_o)
  );
`elsif ERISCV_FPGA
  // en_i is generated by source-clock posedge state and is stable before the
  // next BUFGCE enable sample. Do not infer a falling-edge control register.
  BUFGCE bufgce_i (
    .I (clk_i),
    .CE(en_i),
    .O (clk_o)
  );
`else
  assign clk_o = clk_i & en_i;
`endif

endmodule
