#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025-2026 Xianning Zhan
# SPDX-License-Identifier: BSD-3-Clause

"""Run a local Sky130/OpenROAD place-and-route timing estimate."""

from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import shutil
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
RUN_PPA = Path(__file__).with_name("run_ppa.py")


class OpenRoadError(RuntimeError):
    """The local physical-estimation flow could not complete."""


def quote(value: Path | str) -> str:
    return shlex.quote(str(value))


def tcl_brace(value: Path | str) -> str:
    return "{" + str(value).replace("}", "\\}") + "}"


def run(command: list[str], log: Path) -> str:
    print("+", " ".join(quote(item) for item in command), flush=True)
    completed = subprocess.run(command, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    log.write_text(completed.stdout, encoding="utf-8")
    if completed.returncode:
        raise OpenRoadError(f"command failed ({completed.returncode}); see {log}")
    if re.search(r"^Error:", completed.stdout, flags=re.MULTILINE):
        raise OpenRoadError(f"tool reported an error; see {log}")
    return completed.stdout


def find_pdk_root(explicit_root: Path | None) -> Path:
    if explicit_root is not None:
        candidates = [explicit_root]
    elif os.environ.get("PPA_SKY130_ROOT"):
        candidates = [Path(os.environ["PPA_SKY130_ROOT"])]
    else:
        ppa_home = Path(os.environ.get("PPA_HOME", REPO_ROOT / ".cache" / "ppa"))
        candidates = sorted((ppa_home / "pdks" / "volare" / "sky130" / "versions").glob("*/sky130A"))
    if len(candidates) != 1 or not candidates[0].is_dir():
        raise OpenRoadError(
            "Sky130 PDK root is ambiguous or missing; set PPA_SKY130_ROOT to the sky130A directory"
        )
    return candidates[0].resolve()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--product", choices=("m0", "m1", "m2"), default="m0")
    parser.add_argument("--period-ns", type=float, default=20.0)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--pdk-root", type=Path, help="Sky130A PDK root (or set PPA_SKY130_ROOT)")
    parser.add_argument("--openroad", default="openroad")
    parser.add_argument("--yosys", default="yosys")
    parser.add_argument("--sta", default="sta")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.period_ns <= 0:
        raise SystemExit("--period-ns must be positive")
    if shutil.which(args.openroad) is None:
        raise SystemExit("OpenROAD not found in PATH; source tools/ppa/env.sh first")
    try:
        pdk_root = find_pdk_root(args.pdk_root)
        lib_root = pdk_root / "libs.ref" / "sky130_fd_sc_hd"
        liberty = lib_root / "lib" / "sky130_fd_sc_hd__tt_025C_1v80.lib"
        tech_lef = lib_root / "techlef" / "sky130_fd_sc_hd__nom.tlef"
        cell_lef = lib_root / "lef" / "sky130_fd_sc_hd.lef"
        blackbox = lib_root / "verilog" / "sky130_fd_sc_hd__blackbox.v"
        for required in (liberty, tech_lef, cell_lef, blackbox):
            if not required.is_file():
                raise OpenRoadError(f"missing Sky130 PDK file: {required}")

        output_dir = args.output_dir.resolve()
        output_dir.mkdir(parents=True, exist_ok=True)
        # A failed run must not leave a prior target's successful summary behind.
        (output_dir / "summary.json").unlink(missing_ok=True)
        prep_dir = output_dir / "synthesis"
        run(
            [
                sys.executable,
                str(RUN_PPA),
                "--product",
                args.product,
                "--period-ns",
                str(args.period_ns),
                "--liberty",
                str(liberty),
                "--input-driver-cell",
                "sky130_fd_sc_hd__buf_1",
                "--input-driver-pin",
                "X",
                "--clock-gate-model",
                "sky130",
                "--clock-gate-blackbox",
                str(blackbox),
                "--output-dir",
                str(prep_dir),
                "--yosys",
                args.yosys,
                "--sta",
                args.sta,
            ],
            output_dir / "synthesis.log",
        )

        netlist = prep_dir / "soc_mapped.v"
        constraints = prep_dir / "constraints.sdc"
        tcl = output_dir / "run_openroad.tcl"
        tcl.write_text(
            "\n".join(
                [
                    "# Generated by tools/ppa/run_openroad.py.",
                    f"read_lef {tcl_brace(tech_lef)}",
                    f"read_lef {tcl_brace(cell_lef)}",
                    f"read_liberty {tcl_brace(liberty)}",
                    f"read_verilog {tcl_brace(netlist)}",
                    "link_design soc",
                    f"source {tcl_brace(constraints)}",
                    "initialize_floorplan -utilization 45 -core_space 20 -site unithd",
                    "make_tracks li1 -x_offset 0.23 -x_pitch 0.46 -y_offset 0.17 -y_pitch 0.34",
                    "make_tracks met1 -x_offset 0.17 -x_pitch 0.34 -y_offset 0.17 -y_pitch 0.34",
                    "make_tracks met2 -x_offset 0.23 -x_pitch 0.46 -y_offset 0.23 -y_pitch 0.46",
                    "make_tracks met3 -x_offset 0.34 -x_pitch 0.68 -y_offset 0.34 -y_pitch 0.68",
                    "make_tracks met4 -x_offset 0.46 -x_pitch 0.92 -y_offset 0.46 -y_pitch 0.92",
                    "make_tracks met5 -x_offset 1.70 -x_pitch 3.40 -y_offset 1.70 -y_pitch 3.40",
                    "set_routing_layers -signal met1-met5 -clock met3-met5",
                    "set_wire_rc -signal -layer met2",
                    "set_wire_rc -clock -layer met5",
                    "place_pins -hor_layers met3 -ver_layers met2 -annealing",
                    "global_placement -density 0.50 -timing_driven",
                    "estimate_parasitics -placement",
                    "repair_design -max_utilization 0.65",
                    "detailed_placement",
                    "clock_tree_synthesis -root_buf sky130_fd_sc_hd__clkbuf_16 -buf_list {sky130_fd_sc_hd__clkbuf_8 sky130_fd_sc_hd__clkbuf_4 sky130_fd_sc_hd__clkbuf_2} -repair_clock_nets",
                    "set_propagated_clock [all_clocks]",
                    "global_route -congestion_iterations 100",
                    "estimate_parasitics -global_routing",
                    "puts OR_PRE_REPAIR_SETUP_BEGIN",
                    "report_checks -path_delay max -group_path_count 1 -digits 4",
                    "puts OR_PRE_REPAIR_SETUP_END",
                    "repair_timing -setup -max_utilization 0.65",
                    "detailed_placement",
                    "global_route -congestion_iterations 100",
                    "estimate_parasitics -global_routing",
                    "puts OR_AREA_BEGIN",
                    "report_design_area",
                    "puts OR_AREA_END",
                    "puts OR_SETUP_BEGIN",
                    "report_checks -path_delay max -group_path_count 1 -digits 4",
                    "report_worst_slack -max",
                    "report_tns -max",
                    "puts OR_SETUP_END",
                    "puts OR_HOLD_BEGIN",
                    "report_checks -path_delay min -group_path_count 1 -digits 4",
                    "report_worst_slack -min",
                    "report_tns -min",
                    "puts OR_HOLD_END",
                    f"write_def {tcl_brace(output_dir / 'soc.def')}",
                    f"write_verilog {tcl_brace(output_dir / 'soc_postroute.v')}",
                    "exit",
                    "",
                ]
            ),
            encoding="utf-8",
        )
        log = run([args.openroad, "-no_init", "-exit", str(tcl)], output_dir / "openroad.log")
    except OpenRoadError as exc:
        print(f"OpenROAD PPA FAIL: {exc}", file=sys.stderr)
        return 1

    setup_wns = _marked_number("OR_SETUP", r"worst slack max\s+(-?[0-9.eE+-]+)", log)
    hold_wns = _marked_number("OR_HOLD", r"worst slack min\s+(-?[0-9.eE+-]+)", log)
    area_um2 = _marked_number("OR_AREA", r"Design area\s+([0-9.eE+-]+)", log)
    critical_path_ns = args.period_ns - setup_wns if setup_wns is not None else None
    summary = {
        "product": args.product,
        "top": "soc",
        "clock_period_ns": args.period_ns,
        "pdk_root": str(pdk_root),
        "liberty": str(liberty),
        "setup_wns_ns": setup_wns,
        "hold_wns_ns": hold_wns,
        "critical_path_ns": critical_path_ns,
        "fmax_mhz": 1000.0 / critical_path_ns if critical_path_ns and critical_path_ns > 0 else None,
        "area_um2": area_um2,
        "clock_gate_model": "sky130_fd_sc_hd__dlclkp_2",
        "memory_model": "sram_1rw blackbox; SRAM macro area, timing, LEF, and routing excluded",
        "implementation_scope": "Sky130 standard-cell logic with floorplan, global placement, high-fanout repair, CTS, global-routing RC, and post-CTS setup repair; hold is reported but not repaired. No SRAM macro, PDN, detailed routing, extracted SPEF, IR/EM, or signoff checks",
    }
    (output_dir / "summary.json").write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(summary, indent=2))
    return 0


def _marked_number(marker: str, pattern: str, text: str) -> float | None:
    block = re.search(rf"{marker}_BEGIN(?P<body>[\s\S]*?){marker}_END", text)
    if not block:
        return None
    match = re.search(pattern, block.group("body"), flags=re.IGNORECASE | re.MULTILINE)
    return float(match.group(1)) if match else None


if __name__ == "__main__":
    raise SystemExit(main())
