#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025-2026 Xianning Zhan
# SPDX-License-Identifier: BSD-3-Clause

"""Generate bit-exact binary32 references for M2 radix-2 FFT smoke tests."""

from __future__ import annotations

import argparse
import math
import struct
from pathlib import Path

POINT_CHOICES = (128, 1024)


def f32(value: float) -> float:
    return struct.unpack("<f", struct.pack("<f", float(value)))[0]


def bits(value: float) -> int:
    return struct.unpack("<I", struct.pack("<f", value))[0]


def add(left: float, right: float) -> float:
    return f32(f32(left) + f32(right))


def sub(left: float, right: float) -> float:
    return f32(f32(left) - f32(right))


def mul(left: float, right: float) -> float:
    return f32(f32(left) * f32(right))


def reverse_bits(index: int, log2_points: int) -> int:
    result = 0
    for _ in range(log2_points):
        result = (result << 1) | (index & 1)
        index >>= 1
    return result


def fft(real: list[float], imag: list[float], tw_re: list[float], tw_im: list[float]) -> None:
    points = len(real)
    log2_points = points.bit_length() - 1
    for index in range(points):
        reversed_index = reverse_bits(index, log2_points)
        if reversed_index > index:
            real[index], real[reversed_index] = real[reversed_index], real[index]
            imag[index], imag[reversed_index] = imag[reversed_index], imag[index]

    size = 2
    while size <= points:
        half = size // 2
        step = points // size
        for base in range(0, points, size):
            for offset in range(half):
                even = base + offset
                odd = even + half
                twiddle = offset * step
                product_rr = mul(tw_re[twiddle], real[odd])
                product_ii = mul(tw_im[twiddle], imag[odd])
                product_ri = mul(tw_re[twiddle], imag[odd])
                product_ir = mul(tw_im[twiddle], real[odd])
                temp_re = sub(product_rr, product_ii)
                temp_im = add(product_ri, product_ir)
                old_re = real[even]
                old_im = imag[even]
                real[even] = add(old_re, temp_re)
                imag[even] = add(old_im, temp_im)
                real[odd] = sub(old_re, temp_re)
                imag[odd] = sub(old_im, temp_im)
        size *= 2


def words(name: str, values: list[float]) -> str:
    rows = []
    for offset in range(0, len(values), 4):
        rows.append("  " + ", ".join(f"0x{bits(value):08x}u" for value in values[offset:offset + 4]) + ",")
    return f"static const eriscv_mcu_u32 {name}[FPU_FFT_POINTS] = {{\n" + "\n".join(rows) + "\n};\n"


def output_path(points: int) -> Path:
    root = Path(__file__).resolve().parents[1] / "examples"
    if points == 128:
        return root / "fpu_fft/fpu_fft128_vectors.h"
    return root / f"fpu_fft{points}/fpu_fft{points}_vectors.h"


def generate(points: int) -> None:
    input_re = []
    input_im = []
    for index in range(points):
        angle = 2.0 * math.pi * index / points
        input_re.append(f32(0.55 * math.sin(3.0 * angle) + 0.20 * math.cos(17.0 * angle) + 0.03 * (index % 5)))
        input_im.append(f32(0.35 * math.cos(5.0 * angle) - 0.15 * math.sin(11.0 * angle) - 0.02 * (index % 7)))
    tw_re = [f32(math.cos(-2.0 * math.pi * index / points)) for index in range(points)]
    tw_im = [f32(math.sin(-2.0 * math.pi * index / points)) for index in range(points)]
    reference_re = input_re.copy()
    reference_im = input_im.copy()
    fft(reference_re, reference_im, tw_re, tw_im)

    output_path(points).write_text(
        "/* Generated by tools/generate_fpu_fft_vectors.py; do not edit. */\n"
        f"#define FPU_FFT_POINTS {points}u\n"
        f"#define FPU_FFT_LOG2 {points.bit_length() - 1}u\n"
        f"#define FPU_FFT_LABEL \"FFT{points}\"\n\n" +
        words("fpu_fft_input_re_bits", input_re) + "\n" +
        words("fpu_fft_input_im_bits", input_im) + "\n" +
        words("fpu_fft_twiddle_re_bits", tw_re) + "\n" +
        words("fpu_fft_twiddle_im_bits", tw_im) + "\n" +
        words("fpu_fft_reference_re_bits", reference_re) + "\n" +
        words("fpu_fft_reference_im_bits", reference_im),
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--points", type=int, choices=POINT_CHOICES, default=128)
    args = parser.parse_args()
    generate(args.points)


if __name__ == "__main__":
    main()
